const { Client } = require('pg');
require('dotenv').config();

async function migrate() {
    const client = new Client({
        connectionString: process.env.DATABASE_URL,
        ssl: {
            rejectUnauthorized: false
        }
    });

    try {
        await client.connect();
        console.log('Connected to database.');

        const schema = `
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                telegram_id TEXT UNIQUE NOT NULL,
                username TEXT,
                first_name TEXT,
                created_at INTEGER DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
            );

            CREATE TABLE IF NOT EXISTS groups (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                telegram_id TEXT UNIQUE NOT NULL,
                title TEXT,
                type TEXT,
                created_at INTEGER DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER)
            );

            CREATE TABLE IF NOT EXISTS scans (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT,
                group_id TEXT,
                ticker TEXT,
                ca TEXT,
                timestamp INTEGER DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
                FOREIGN KEY (user_id) REFERENCES users(telegram_id),
                FOREIGN KEY (group_id) REFERENCES groups(telegram_id)
            );

            CREATE TABLE IF NOT EXISTS ledger (
                user_id TEXT PRIMARY KEY,
                virtual_balance REAL DEFAULT 0,
                last_updated INTEGER DEFAULT CAST(EXTRACT(EPOCH FROM NOW()) AS INTEGER),
                FOREIGN KEY (user_id) REFERENCES users(telegram_id)
            );
        `;

        await client.query(schema);
        console.log('Migration completed successfully.');
    } catch (err) {
        console.error('Migration failed:', err);
    } finally {
        await client.end();
    }
}

migrate();
