const { createClient } = require('@supabase/supabase-js');
const { Pool } = require('pg');
require('dotenv').config();

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

async function runMigration() {
  const client = await pool.connect();
  try {
    console.log('Running migration...');
    
    // Add wallet columns to users table
    await client.query(`
      CREATE TABLE IF NOT EXISTS public.users (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          telegram_id TEXT UNIQUE NOT NULL,
          username TEXT,
          first_name TEXT,
          wallet_sol_pub TEXT,
          wallet_sol_priv TEXT,
          wallet_base_pub TEXT,
          wallet_base_priv TEXT,
          created_at TIMESTAMPTZ DEFAULT NOW()
      );
      
      -- Alter table to add columns if they don't exist (idempotent)
      DO $$ 
      BEGIN 
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='users' AND column_name='wallet_sol_pub') THEN
          ALTER TABLE public.users ADD COLUMN wallet_sol_pub TEXT;
          ALTER TABLE public.users ADD COLUMN wallet_sol_priv TEXT;
          ALTER TABLE public.users ADD COLUMN wallet_base_pub TEXT;
          ALTER TABLE public.users ADD COLUMN wallet_base_priv TEXT;
        END IF;
      END $$;

      CREATE TABLE IF NOT EXISTS public.groups (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          telegram_id TEXT UNIQUE NOT NULL,
          title TEXT,
          type TEXT,
          created_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE TABLE IF NOT EXISTS public.scans (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id TEXT, 
          group_id TEXT,
          ticker TEXT,
          ca TEXT,
          timestamp BIGINT DEFAULT EXTRACT(EPOCH FROM NOW()),
          FOREIGN KEY (user_id) REFERENCES public.users(telegram_id),
          FOREIGN KEY (group_id) REFERENCES public.groups(telegram_id)
      );
    `);
    
    console.log('Migration complete!');
  } catch (err) {
    console.error('Migration failed:', err);
  } finally {
    client.release();
    pool.end();
  }
}

runMigration();
